In [2]:
import numpy as np
import time
import sys

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
# Execution performance
size = 1_000_000
#python list
py_list = list(range(size)) # [1, 2, 3, 4, ...]
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end-start}s")
#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"NumPy array time = {end-start}")

Python list time = 0.3934972286224365s
NumPy array time = 0.014534473419189453


In [10]:
# memory
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
NumPy array size = 8000000 bytes


In [16]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64 (7,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [35]:
# Create
arr1 = np.zeros((2, 3), dtype="int64")
print(arr1, arr1.shape)

arr4 = np.ones((5,))
print(arr4, arr4.shape)

arr5 = np.full((3,4), 100)
print(arr5, arr5.shape)

arr6 = np.eye((4), dtype="int64") #identity matrix
print(arr6, arr6.shape)

arr7 = np.arange(1, 11, 2) #range elements
print(arr7, arr7.shape)

arr8 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr8, arr8.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] (4, 4)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [38]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape) #dimensions = m x n
print(arr.size) #tot els - 9
print(arr.dtype) #data type
print(arr.ndim) #no. of dimensions
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [40]:
# Operations on Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)
reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)
flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [44]:
# Indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0], arr[3], sep=" | ")
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[1][1], arr2[0][2], arr2[0][0], sep=" | ")

1 | 4
5 | 3 | 1


In [48]:
# Fancy Indexing
idx = [0, 1, 3]
print(arr[idx])

# Boolean Indexing
print(arr[arr%2 != 0])

[1 2 4]
[1 3 5 7]


In [51]:
# Slicing
print(arr[1:6:3])

[2 5]


In [54]:
# Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
sub_list[0] = 200
print("Python Lists =", sub_list, nums)

arr = np.array(nums)
sub_arr = arr[1:3]
sub_arr[0] = 200
sub_arr2 = arr[1:3].copy()
sub_arr2[0] = 300
print("NumPy arrays =", sub_arr, sub_arr2, arr)

Python Lists = [200, 3] [1, 2, 3, 4, 5]
NumPy arrays = [200   3] [300   3] [  1 200   3   4   5]


In [58]:
# Multi-dimensional arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis=0)
sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_columns, sum_of_rows)
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18] [ 6 15 24]
[[2]
 [5]]


In [8]:
# 3D Array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) #2 x 3 x 2
print(arr3D, arr3D.shape)

#indexing
print(arr3D[1][1][0])
#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first col from both layers
arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [11]:
# Vectorization
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9 ,10])
print(arr**2)
print(arr+arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [15]:
# Broadcasting
print(arr+7)
arr2 = np.array([[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr+arr2)

[ 8  9 10 11 12]
[[ 7  9 11 13 15]
 [12 14 16 18 20]]


In [20]:
# Normalize
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print(np.mean(normalized_arr))
print(np.std(normalized_arr))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0


In [31]:
# Mathematical Functions
#aggrregation
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

#power
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

#log
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

#rounding
print(np.round(3.54))
print(np.ceil(3.54))
print(np.floor(3.54))
print(np.trunc(3.54))

#extras
print(np.unique(arr)) # set working
print(np.sort(arr))
print(np.abs(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
4.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
